//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Genesis.Orders
{

    public partial class Order : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        Customer fCustomerId;
        [Association(@"OrderReferencesCustomer")]
        public Customer CustomerId
        {
            get { return fCustomerId; }
            set { SetPropertyValue<Customer>(nameof(CustomerId), ref fCustomerId, value); }
        }
        string fReferenceNumber;
        [Size(50)]
        public string ReferenceNumber
        {
            get { return fReferenceNumber; }
            set { SetPropertyValue<string>(nameof(ReferenceNumber), ref fReferenceNumber, value); }
        }
        decimal fOrderValue;
        public decimal OrderValue
        {
            get { return fOrderValue; }
            set { SetPropertyValue<decimal>(nameof(OrderValue), ref fOrderValue, value); }
        }
        DateTime fOrderDate;
        public DateTime OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref fOrderDate, value); }
        }
    }

}
